# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testnbdev3',
                'doc_host': 'https://perceptualrobots.github.io',
                'git_url': 'https://github.com/perceptualrobots/testnbdev3',
                'lib_path': 'testnbdev3'},
  'syms': {'testnbdev3.core': {'testnbdev3.core.foo': ('core.html#foo', 'testnbdev3/core.py')}}}
